// The Docket API contract. Any language with a gRPC toolchain can generate a
// client from this file and enqueue or inspect jobs without touching the
// database directly.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: docket.proto

package docketv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobState int32

const (
	JobState_JOB_STATE_UNSPECIFIED JobState = 0
	JobState_JOB_STATE_PENDING     JobState = 1
	JobState_JOB_STATE_RUNNING     JobState = 2
	JobState_JOB_STATE_SUCCEEDED   JobState = 3
	JobState_JOB_STATE_DEAD        JobState = 4
)

// Enum value maps for JobState.
var (
	JobState_name = map[int32]string{
		0: "JOB_STATE_UNSPECIFIED",
		1: "JOB_STATE_PENDING",
		2: "JOB_STATE_RUNNING",
		3: "JOB_STATE_SUCCEEDED",
		4: "JOB_STATE_DEAD",
	}
	JobState_value = map[string]int32{
		"JOB_STATE_UNSPECIFIED": 0,
		"JOB_STATE_PENDING":     1,
		"JOB_STATE_RUNNING":     2,
		"JOB_STATE_SUCCEEDED":   3,
		"JOB_STATE_DEAD":        4,
	}
)

func (x JobState) Enum() *JobState {
	p := new(JobState)
	*p = x
	return p
}

func (x JobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobState) Descriptor() protoreflect.EnumDescriptor {
	return file_docket_proto_enumTypes[0].Descriptor()
}

func (JobState) Type() protoreflect.EnumType {
	return &file_docket_proto_enumTypes[0]
}

func (x JobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobState.Descriptor instead.
func (JobState) EnumDescriptor() ([]byte, []int) {
	return file_docket_proto_rawDescGZIP(), []int{0}
}

type EnqueueRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Queue          string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`                                         // default "default"
	Payload        []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                                     // JSON; default {}
	Priority       int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`                                  // higher runs first
	MaxAttempts    int32                  `protobuf:"varint,4,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`         // default 5
	RunAt          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=run_at,json=runAt,proto3" json:"run_at,omitempty"`                            // unset = as soon as possible
	IdempotencyKey string                 `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // optional; dedupes repeat enqueues
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnqueueRequest) Reset() {
	*x = EnqueueRequest{}
	mi := &file_docket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRequest) ProtoMessage() {}

func (x *EnqueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRequest.ProtoReflect.Descriptor instead.
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return file_docket_proto_rawDescGZIP(), []int{0}
}

func (x *EnqueueRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *EnqueueRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EnqueueRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *EnqueueRequest) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *EnqueueRequest) GetRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RunAt
	}
	return nil
}

func (x *EnqueueRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type EnqueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Deduplicated  bool                   `protobuf:"varint,2,opt,name=deduplicated,proto3" json:"deduplicated,omitempty"` // true if an existing job with the same key was returned
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueResponse) Reset() {
	*x = EnqueueResponse{}
	mi := &file_docket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueResponse) ProtoMessage() {}

func (x *EnqueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueResponse.ProtoReflect.Descriptor instead.
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return file_docket_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueResponse) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *EnqueueResponse) GetDeduplicated() bool {
	if x != nil {
		return x.Deduplicated
	}
	return false
}

type Job struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Queue          string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	Payload        []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	State          JobState               `protobuf:"varint,4,opt,name=state,proto3,enum=docket.v1.JobState" json:"state,omitempty"`
	Priority       int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Attempts       int32                  `protobuf:"varint,6,opt,name=attempts,proto3" json:"attempts,omitempty"`
	MaxAttempts    int32                  `protobuf:"varint,7,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	RunAt          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=run_at,json=runAt,proto3" json:"run_at,omitempty"`
	LeaseExpiresAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"` // unset unless running
	WorkerId       string                 `protobuf:"bytes,10,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`                    // empty unless running
	LastError      string                 `protobuf:"bytes,11,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"` // unset unless succeeded
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_docket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_docket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_docket_proto_rawDescGZIP(), []int{2}
}

func (x *Job) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Job) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *Job) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Job) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *Job) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Job) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *Job) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *Job) GetRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RunAt
	}
	return nil
}

func (x *Job) GetLeaseExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return nil
}

func (x *Job) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Job) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Job) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Job) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_docket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_docket_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type GetJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_docket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_docket_proto_rawDescGZIP(), []int{4}
}

func (x *GetJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"` // empty = all queues
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_docket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_docket_proto_rawDescGZIP(), []int{5}
}

func (x *StatsRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

type QueueDepth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	State         JobState               `protobuf:"varint,2,opt,name=state,proto3,enum=docket.v1.JobState" json:"state,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueDepth) Reset() {
	*x = QueueDepth{}
	mi := &file_docket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueDepth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueDepth) ProtoMessage() {}

func (x *QueueDepth) ProtoReflect() protoreflect.Message {
	mi := &file_docket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueDepth.ProtoReflect.Descriptor instead.
func (*QueueDepth) Descriptor() ([]byte, []int) {
	return file_docket_proto_rawDescGZIP(), []int{6}
}

func (x *QueueDepth) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *QueueDepth) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *QueueDepth) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Depths        []*QueueDepth          `protobuf:"bytes,1,rep,name=depths,proto3" json:"depths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_docket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_docket_proto_rawDescGZIP(), []int{7}
}

func (x *StatsResponse) GetDepths() []*QueueDepth {
	if x != nil {
		return x.Depths
	}
	return nil
}

type RequeueDeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequeueDeadRequest) Reset() {
	*x = RequeueDeadRequest{}
	mi := &file_docket_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequeueDeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequeueDeadRequest) ProtoMessage() {}

func (x *RequeueDeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docket_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequeueDeadRequest.ProtoReflect.Descriptor instead.
func (*RequeueDeadRequest) Descriptor() ([]byte, []int) {
	return file_docket_proto_rawDescGZIP(), []int{8}
}

func (x *RequeueDeadRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type RequeueDeadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequeueDeadResponse) Reset() {
	*x = RequeueDeadResponse{}
	mi := &file_docket_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequeueDeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequeueDeadResponse) ProtoMessage() {}

func (x *RequeueDeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docket_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequeueDeadResponse.ProtoReflect.Descriptor instead.
func (*RequeueDeadResponse) Descriptor() ([]byte, []int) {
	return file_docket_proto_rawDescGZIP(), []int{9}
}

var File_docket_proto protoreflect.FileDescriptor

const file_docket_proto_rawDesc = "" +
	"\n" +
	"\fdocket.proto\x12\tdocket.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x01\n" +
	"\x0eEnqueueRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12!\n" +
	"\fmax_attempts\x18\x04 \x01(\x05R\vmaxAttempts\x121\n" +
	"\x06run_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05runAt\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\"L\n" +
	"\x0fEnqueueResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12\"\n" +
	"\fdeduplicated\x18\x02 \x01(\bR\fdeduplicated\"\xfa\x03\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12)\n" +
	"\x05state\x18\x04 \x01(\x0e2\x13.docket.v1.JobStateR\x05state\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x1a\n" +
	"\battempts\x18\x06 \x01(\x05R\battempts\x12!\n" +
	"\fmax_attempts\x18\a \x01(\x05R\vmaxAttempts\x121\n" +
	"\x06run_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x05runAt\x12D\n" +
	"\x10lease_expires_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0eleaseExpiresAt\x12\x1b\n" +
	"\tworker_id\x18\n" +
	" \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"last_error\x18\v \x01(\tR\tlastError\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fcompleted_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"&\n" +
	"\rGetJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\"2\n" +
	"\x0eGetJobResponse\x12 \n" +
	"\x03job\x18\x01 \x01(\v2\x0e.docket.v1.JobR\x03job\"$\n" +
	"\fStatsRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\"c\n" +
	"\n" +
	"QueueDepth\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12)\n" +
	"\x05state\x18\x02 \x01(\x0e2\x13.docket.v1.JobStateR\x05state\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\">\n" +
	"\rStatsResponse\x12-\n" +
	"\x06depths\x18\x01 \x03(\v2\x15.docket.v1.QueueDepthR\x06depths\"+\n" +
	"\x12RequeueDeadRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\"\x15\n" +
	"\x13RequeueDeadResponse*\x80\x01\n" +
	"\bJobState\x12\x19\n" +
	"\x15JOB_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11JOB_STATE_PENDING\x10\x01\x12\x15\n" +
	"\x11JOB_STATE_RUNNING\x10\x02\x12\x17\n" +
	"\x13JOB_STATE_SUCCEEDED\x10\x03\x12\x12\n" +
	"\x0eJOB_STATE_DEAD\x10\x042\x93\x02\n" +
	"\x06Docket\x12@\n" +
	"\aEnqueue\x12\x19.docket.v1.EnqueueRequest\x1a\x1a.docket.v1.EnqueueResponse\x12=\n" +
	"\x06GetJob\x12\x18.docket.v1.GetJobRequest\x1a\x19.docket.v1.GetJobResponse\x12:\n" +
	"\x05Stats\x12\x17.docket.v1.StatsRequest\x1a\x18.docket.v1.StatsResponse\x12L\n" +
	"\vRequeueDead\x12\x1d.docket.v1.RequeueDeadRequest\x1a\x1e.docket.v1.RequeueDeadResponseB4Z2github.com/varshakodi/docket/api/docketv1;docketv1b\x06proto3"

var (
	file_docket_proto_rawDescOnce sync.Once
	file_docket_proto_rawDescData []byte
)

func file_docket_proto_rawDescGZIP() []byte {
	file_docket_proto_rawDescOnce.Do(func() {
		file_docket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docket_proto_rawDesc), len(file_docket_proto_rawDesc)))
	})
	return file_docket_proto_rawDescData
}

var file_docket_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_docket_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_docket_proto_goTypes = []any{
	(JobState)(0),                 // 0: docket.v1.JobState
	(*EnqueueRequest)(nil),        // 1: docket.v1.EnqueueRequest
	(*EnqueueResponse)(nil),       // 2: docket.v1.EnqueueResponse
	(*Job)(nil),                   // 3: docket.v1.Job
	(*GetJobRequest)(nil),         // 4: docket.v1.GetJobRequest
	(*GetJobResponse)(nil),        // 5: docket.v1.GetJobResponse
	(*StatsRequest)(nil),          // 6: docket.v1.StatsRequest
	(*QueueDepth)(nil),            // 7: docket.v1.QueueDepth
	(*StatsResponse)(nil),         // 8: docket.v1.StatsResponse
	(*RequeueDeadRequest)(nil),    // 9: docket.v1.RequeueDeadRequest
	(*RequeueDeadResponse)(nil),   // 10: docket.v1.RequeueDeadResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_docket_proto_depIdxs = []int32{
	11, // 0: docket.v1.EnqueueRequest.run_at:type_name -> google.protobuf.Timestamp
	0,  // 1: docket.v1.Job.state:type_name -> docket.v1.JobState
	11, // 2: docket.v1.Job.run_at:type_name -> google.protobuf.Timestamp
	11, // 3: docket.v1.Job.lease_expires_at:type_name -> google.protobuf.Timestamp
	11, // 4: docket.v1.Job.created_at:type_name -> google.protobuf.Timestamp
	11, // 5: docket.v1.Job.completed_at:type_name -> google.protobuf.Timestamp
	3,  // 6: docket.v1.GetJobResponse.job:type_name -> docket.v1.Job
	0,  // 7: docket.v1.QueueDepth.state:type_name -> docket.v1.JobState
	7,  // 8: docket.v1.StatsResponse.depths:type_name -> docket.v1.QueueDepth
	1,  // 9: docket.v1.Docket.Enqueue:input_type -> docket.v1.EnqueueRequest
	4,  // 10: docket.v1.Docket.GetJob:input_type -> docket.v1.GetJobRequest
	6,  // 11: docket.v1.Docket.Stats:input_type -> docket.v1.StatsRequest
	9,  // 12: docket.v1.Docket.RequeueDead:input_type -> docket.v1.RequeueDeadRequest
	2,  // 13: docket.v1.Docket.Enqueue:output_type -> docket.v1.EnqueueResponse
	5,  // 14: docket.v1.Docket.GetJob:output_type -> docket.v1.GetJobResponse
	8,  // 15: docket.v1.Docket.Stats:output_type -> docket.v1.StatsResponse
	10, // 16: docket.v1.Docket.RequeueDead:output_type -> docket.v1.RequeueDeadResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_docket_proto_init() }
func file_docket_proto_init() {
	if File_docket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docket_proto_rawDesc), len(file_docket_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docket_proto_goTypes,
		DependencyIndexes: file_docket_proto_depIdxs,
		EnumInfos:         file_docket_proto_enumTypes,
		MessageInfos:      file_docket_proto_msgTypes,
	}.Build()
	File_docket_proto = out.File
	file_docket_proto_goTypes = nil
	file_docket_proto_depIdxs = nil
}
