// The Docket API contract. Any language with a gRPC toolchain can generate a
// client from this file and enqueue or inspect jobs without touching the
// database directly.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: docket.proto

package docketv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Docket_Enqueue_FullMethodName     = "/docket.v1.Docket/Enqueue"
	Docket_GetJob_FullMethodName      = "/docket.v1.Docket/GetJob"
	Docket_Stats_FullMethodName       = "/docket.v1.Docket/Stats"
	Docket_RequeueDead_FullMethodName = "/docket.v1.Docket/RequeueDead"
)

// DocketClient is the client API for Docket service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocketClient interface {
	// Add a job. Returns immediately after the job is durably stored.
	Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error)
	// Fetch one job by ID.
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error)
	// Backlog per queue and state.
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// Give a dead job a fresh attempt budget.
	RequeueDead(ctx context.Context, in *RequeueDeadRequest, opts ...grpc.CallOption) (*RequeueDeadResponse, error)
}

type docketClient struct {
	cc grpc.ClientConnInterface
}

func NewDocketClient(cc grpc.ClientConnInterface) DocketClient {
	return &docketClient{cc}
}

func (c *docketClient) Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueResponse)
	err := c.cc.Invoke(ctx, Docket_Enqueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docketClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobResponse)
	err := c.cc.Invoke(ctx, Docket_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docketClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, Docket_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docketClient) RequeueDead(ctx context.Context, in *RequeueDeadRequest, opts ...grpc.CallOption) (*RequeueDeadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequeueDeadResponse)
	err := c.cc.Invoke(ctx, Docket_RequeueDead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocketServer is the server API for Docket service.
// All implementations must embed UnimplementedDocketServer
// for forward compatibility.
type DocketServer interface {
	// Add a job. Returns immediately after the job is durably stored.
	Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error)
	// Fetch one job by ID.
	GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error)
	// Backlog per queue and state.
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	// Give a dead job a fresh attempt budget.
	RequeueDead(context.Context, *RequeueDeadRequest) (*RequeueDeadResponse, error)
	mustEmbedUnimplementedDocketServer()
}

// UnimplementedDocketServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocketServer struct{}

func (UnimplementedDocketServer) Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enqueue not implemented")
}
func (UnimplementedDocketServer) GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedDocketServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedDocketServer) RequeueDead(context.Context, *RequeueDeadRequest) (*RequeueDeadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequeueDead not implemented")
}
func (UnimplementedDocketServer) mustEmbedUnimplementedDocketServer() {}
func (UnimplementedDocketServer) testEmbeddedByValue()                {}

// UnsafeDocketServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocketServer will
// result in compilation errors.
type UnsafeDocketServer interface {
	mustEmbedUnimplementedDocketServer()
}

func RegisterDocketServer(s grpc.ServiceRegistrar, srv DocketServer) {
	// If the following call panics, it indicates UnimplementedDocketServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Docket_ServiceDesc, srv)
}

func _Docket_Enqueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocketServer).Enqueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Docket_Enqueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocketServer).Enqueue(ctx, req.(*EnqueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Docket_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocketServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Docket_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocketServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Docket_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocketServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Docket_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocketServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Docket_RequeueDead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequeueDeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocketServer).RequeueDead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Docket_RequeueDead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocketServer).RequeueDead(ctx, req.(*RequeueDeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Docket_ServiceDesc is the grpc.ServiceDesc for Docket service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Docket_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "docket.v1.Docket",
	HandlerType: (*DocketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enqueue",
			Handler:    _Docket_Enqueue_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _Docket_GetJob_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _Docket_Stats_Handler,
		},
		{
			MethodName: "RequeueDead",
			Handler:    _Docket_RequeueDead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "docket.proto",
}
